FROM python:2.7-wheezy
RUN pip install jsonpickle 
RUN pip install leveldb 
RUN pip install Twisted==16.0.0 
RUN pip install blessings 
RUN pip install statistics
WORKDIR /home/osboxes/Projects/QRL
CMD bash


